#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDC_EDIT_FILTER                         1001
#define IDC_LISTVIEW_INFILE                     1002
#define IDC_BUTTON_INFILE_ADD                   1004
#define IDD_MAIN                                1041
#define IDR_MENU_MAIN                           1041
#define IDM_EXIT                                40000
#define IDS_SET_INFILE                          40000
#define IDM_SORT_CAPTION                        40001
#define IDS_SET_OUTFILE                         40001
#define IDM_SORT_IP                             40002
#define IDS_FAILED_FILE_READ                    40002
#define IDM_CHECK_DUP_IP                        40003
#define IDS_FAILED_FILE_WRITE                   40003
#define IDM_SAVE_REPLACE                        40004
#define IDS_FILE_PATH                           40004
#define IDM_SAVE_APPEND                         40005
#define IDS_FILE_NAME                           40005
#define IDM_CHECK_INFILE                        40006
#define IDS_EXPFILT_PGLIST                      40006
#define IDM_OUTPUT                              40007
#define IDS_OUTPUT_COMPLETE                     40007
#define IDM_CHECK_AND_OUTPUT                    40008
#define IDS_EXECUTING                           40008
#define IDS_CHECK_FOUND_ERROR                   40009
#define IDS_CHECK_NOTFOUND_ERROR                40010
#define IDS_CHECK_COMPLETE                      40011
#define IDS_CHECK_ERROR_SYNTAX                  40012
#define IDS_CHECK_ERROR_IP                      40013
#define IDS_CHECK_ERROR_SYNTAX_RESTORABLE       40014
#define IDC_EDIT_OUTFILE                        40022
#define IDC_EDIT_RESULT                         40026
#define IDC_BUTTON_INFILE_DEL                   40027
#define IDC_BUTTON_INFILE_CLEAR                 40028
#define IDC_BUTTON_OUTFILE_REF                  40029
#define IDC_BUTTON_FILTER_CLEAR                 40030
#define IDC_RADIO_FILTER_AND                    40031
#define IDC_RADIO_FILTER_OR                     40032
#define IDC_CHECK_FILTER_DEL                    40033
